spring:
  application:
    name: currency-conversion-service
  config:
    import: configserver:http://localhost:8888

server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
