spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configs
server:
  port: 8888
